### ISSUE TITLE
npm run build -> Service account object must contain a string "project_id" property.

### ISSUE THREAD

**Issue by SperenzaNarra** [NathanKun/resonance-columba#111]
```
npm run build

> resonance-columba@0.0.0 build
> next build

   ▲ Next.js 14.1.3
   - Environments: .env.local

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
   Collecting page data  .FirebaseAppError: Service account object must contain a string "project_id" property.
    at new ServiceAccount (C:\Users\drop\Desktop\git\resonance-columba\node_modules\firebase-admin\lib\app\credential-internal.js:145:19)
    at new ServiceAccountCredential (C:\Users\drop\Desktop\git\resonance-columba\node_modules\firebase-admin\lib\app\credential-internal.js:70:15)
    at cert (C:\Users\drop\Desktop\git\resonance-columba\node_modules\firebase-admin\lib\app\credential-factory.js:103:54)
    at 27098 (C:\Users\drop\Desktop\git\resonance-columba\.next\server\chunks\416.js:1:13609)
    at t (C:\Users\drop\Desktop\git\resonance-columba\.next\server\webpack-runtime.js:1:128)
    at 52753 (C:\Users\drop\Desktop\git\resonance-columba\.next\server\app\api\set-price\route.js:1:590)
    at t (C:\Users\drop\Desktop\git\resonance-columba\.next\server\webpack-runtime.js:1:128)
    at i (C:\Users\drop\Desktop\git\resonance-columba\.next\server\app\api\set-price\route.js:1:18790)
    at C:\Users\drop\Desktop\git\resonance-columba\.next\server\app\api\set-price\route.js:1:18821
    at t.X (C:\Users\drop\Desktop\git\resonance-columba\.next\server\webpack-runtime.js:1:1206) {
  errorInfo: {
    code: 'app/invalid-credential',
    message: 'Service account object must contain a string "project_id" property.'
  },
  codePrefix: 'app'
}

> Build error occurred
Error: Failed to collect page data for /api/set-price
    at C:\Users\drop\Desktop\git\resonance-columba\node_modules\next\dist\build\utils.js:1258:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
   Collecting page data  .
```

以上情况我去谷歌查了 https://github.com/firebase/firebase-admin-node/issues/855#issuecomment-615404826
顺着去查翻到了 firebase\app.ts ，没发现有什么问题，但就是报错

**Comment by SperenzaNarra** [comment]
哦我明白了是我没有账号，打扰了

**Comment by NathanKun** [comment]
本地开发可以使用firebase emulator
https://firebase.google.com/docs/emulator-suite/connect_firestore?hl=zh-cn#admin_sdks
请查看Admin SDK 部分。
